import { Post } from "./types/post";

// 根据帖子内容手动分配最适合的分类
export const mockPosts: Post[] = [
  {
    id: 1,
    title: "欧洲度过白天，夜晚属于国内",
    content: "到欧洲以后第一次知道的事",
    author: "贾斯博Jasper",
    likes: 1000,
    imageUrl: "https://picsum.photos/300/400?random=1",
    category: "travel", // 旅行
  },
  {
    id: 2,
    title: "幸好一开始就说好我是外国人",
    content: "分享国外经历",
    author: "StevenOO",
    likes: 1000,
    imageUrl: "https://picsum.photos/300/400?random=2",
    category: "travel", // 旅行
  },
  {
    id: 3,
    title: "底妆基础 彩妆就...",
    content: "美妆小技巧",
    author: "Enndme",
    likes: 1000,
    imageUrl: "https://picsum.photos/300/400?random=3",
    category: "makeup", // 彩妆
  },
  {
    id: 4,
    title: "卧室里的温柔风，陪你慢慢醒来",
    content: "中古风隐形风扇灯",
    author: "大米的家装模版",
    likes: 1000,
    imageUrl: "https://picsum.photos/300/400?random=4",
    category: "home", // 家居
  },
  {
    id: 5,
    title: "长得甚钝，别的就不基础",
    content: "猫咪日常",
    author: "JOJO小咪弟",
    likes: 1000,
    imageUrl: "https://picsum.photos/300/400?random=5",
    category: "recommend", // 推荐（通用内容）
  },
  {
    id: 6,
    title: "拳皇99：李香绯的必杀技有百连",
    content: "游戏解说",
    author: "生生游戏解说",
    likes: 10,
    imageUrl: "https://picsum.photos/400/300?random=6",
    category: "game", // 游戏
  },
  {
    id: 7,
    title: "流浪食记",
    content: "美食分享",
    author: "某某美食家",
    likes: 500,
    imageUrl: "https://picsum.photos/400/300?random=7",
    category: "food", // 美食
  },
  {
    id: 8,
    title: "浙大机器狗花样迎新",
    content: "旅行季中超利索",
    author: "校园君",
    likes: 800,
    imageUrl: "https://picsum.photos/400/300?random=8",
    category: "recommend", // 推荐（通用内容）
  },
  {
    id: 9,
    title: "美妆灵感",
    content: "妆容分享",
    author: "Anns灵感妆",
    likes: 1200,
    imageUrl: "https://picsum.photos/400/300?random=9",
    category: "makeup", // 彩妆
  },
  // recommend分类 (15条)
  {
    id: 10,
    title: "2023年度十大生活好物推荐",
    content: "提升幸福感的实用单品",
    author: "生活家小A",
    likes: 5600,
    imageUrl: "https://picsum.photos/400/300?random=10",
    category: "recommend",
  },
  {
    id: 11,
    title: "打工人必备的高效午休技巧",
    content: "15分钟恢复满满能量",
    author: "效率达人",
    likes: 3200,
    imageUrl: "https://picsum.photos/400/300?random=11",
    category: "recommend",
  },
  {
    id: 12,
    title: "新手必看的理财入门指南",
    content: "从0开始学习资产管理",
    author: "财商教练",
    likes: 4100,
    imageUrl: "https://picsum.photos/400/300?random=12",
    category: "recommend",
  },
  {
    id: 13,
    title: "治愈系纪录片推荐，周末宅家必看",
    content: "5部让人内心平静的佳作",
    author: "影视迷",
    likes: 2800,
    imageUrl: "https://picsum.photos/400/300?random=13",
    category: "recommend",
  },
  {
    id: 14,
    title: "提升气质的5个小习惯",
    content: "坚持一个月就能看到变化",
    author: "礼仪老师",
    likes: 6300,
    imageUrl: "https://picsum.photos/400/300?random=14",
    category: "recommend",
  },
  {
    id: 15,
    title: "适合上班族的低成本副业",
    content: "利用碎片时间增加收入",
    author: "斜杠青年",
    likes: 7200,
    imageUrl: "https://picsum.photos/400/300?random=15",
    category: "recommend",
  },
  {
    id: 16,
    title: "夏日防蚊全攻略",
    content: "告别蚊虫烦恼的实用方法",
    author: "生活小妙招",
    likes: 3500,
    imageUrl: "https://picsum.photos/400/300?random=16",
    category: "recommend",
  },
  {
    id: 17,
    title: "5款免费实用的手机APP推荐",
    content: "涵盖学习、工作、生活",
    author: "科技达人",
    likes: 2900,
    imageUrl: "https://picsum.photos/400/300?random=17",
    category: "recommend",
  },
  {
    id: 18,
    title: "如何培养孩子的阅读习惯",
    content: "从兴趣出发的实用建议",
    author: "育儿专家",
    likes: 4700,
    imageUrl: "https://picsum.photos/400/300?random=18",
    category: "recommend",
  },
  {
    id: 19,
    title: "居家必备的急救小知识",
    content: "关键时刻能派上用场",
    author: "医护工作者",
    likes: 5100,
    imageUrl: "https://picsum.photos/400/300?random=19",
    category: "recommend",
  },
  {
    id: 20,
    title: "高效整理衣柜的方法",
    content: "告别混乱，轻松找到想穿的衣服",
    author: "整理师",
    likes: 3800,
    imageUrl: "https://picsum.photos/400/300?random=20",
    category: "recommend",
  },
  {
    id: 21,
    title: "适合零基础的乐器推荐",
    content: "容易上手的几种乐器",
    author: "音乐老师",
    likes: 2600,
    imageUrl: "https://picsum.photos/400/300?random=21",
    category: "recommend",
  },
  {
    id: 22,
    title: "缓解颈椎疼痛的几个小动作",
    content: "久坐族必备",
    author: "康复医师",
    likes: 6400,
    imageUrl: "https://picsum.photos/400/300?random=22",
    category: "recommend",
  },
  {
    id: 23,
    title: "家庭收纳神器大公开",
    content: "让小户型也能井井有条",
    author: "收纳达人",
    likes: 3300,
    imageUrl: "https://picsum.photos/400/300?random=23",
    category: "recommend",
  },
  {
    id: 24,
    title: "10分钟快手早餐做法",
    content: "营养又美味",
    author: "美食博主",
    likes: 4200,
    imageUrl: "https://picsum.photos/400/300?random=24",
    category: "recommend",
  },

  // fashion分类 (12条)
  {
    id: 25,
    title: "春季必备的5件基础单品",
    content: "百搭实用，轻松应对各种场合",
    author: "时尚编辑",
    likes: 3200,
    imageUrl: "https://picsum.photos/400/300?random=25",
    category: "fashion",
  },
  {
    id: 26,
    title: "小个子穿搭技巧",
    content: "显高显瘦的秘诀",
    author: "穿搭博主",
    likes: 5800,
    imageUrl: "https://picsum.photos/400/300?random=26",
    category: "fashion",
  },
  {
    id: 27,
    title: "职场女性的商务休闲风",
    content: "专业又不失个性",
    author: "职场时尚顾问",
    likes: 2900,
    imageUrl: "https://picsum.photos/400/300?random=27",
    category: "fashion",
  },
  {
    id: 28,
    title: "夏日连衣裙选购指南",
    content: "不同身材的选择建议",
    author: "服装设计师",
    likes: 4100,
    imageUrl: "https://picsum.photos/400/300?random=28",
    category: "fashion",
  },
  {
    id: 29,
    title: "男士简约穿搭技巧",
    content: "不用费心也能很有型",
    author: "男装搭配师",
    likes: 2700,
    imageUrl: "https://picsum.photos/400/300?random=29",
    category: "fashion",
  },
  {
    id: 30,
    title: "配饰如何提升整体造型",
    content: "小细节大作用",
    author: "时尚达人",
    likes: 3500,
    imageUrl: "https://picsum.photos/400/300?random=30",
    category: "fashion",
  },
  {
    id: 31,
    title: "秋季风衣的多种穿法",
    content: "一件风衣穿出不同风格",
    author: "造型师",
    likes: 4200,
    imageUrl: "https://picsum.photos/400/300?random=31",
    category: "fashion",
  },
  {
    id: 32,
    title: "微胖女生的显瘦穿搭",
    content: "扬长避短的搭配法则",
    author: "大码模特",
    likes: 5300,
    imageUrl: "https://picsum.photos/400/300?random=32",
    category: "fashion",
  },
  {
    id: 33,
    title: "复古风穿搭元素解析",
    content: "如何穿出高级复古感",
    author: "复古爱好者",
    likes: 3800,
    imageUrl: "https://picsum.photos/400/300?random=33",
    category: "fashion",
  },
  {
    id: 34,
    title: "运动鞋搭配技巧",
    content: "舒适与时尚并存",
    author: "潮流博主",
    likes: 4600,
    imageUrl: "https://picsum.photos/400/300?random=34",
    category: "fashion",
  },
  {
    id: 35,
    title: "冬季羽绒服的时尚穿法",
    content: "告别臃肿，温暖又时髦",
    author: "冬季穿搭达人",
    likes: 3100,
    imageUrl: "https://picsum.photos/400/300?random=35",
    category: "fashion",
  },
  {
    id: 36,
    title: "色彩搭配入门指南",
    content: "新手也能掌握的配色技巧",
    author: "色彩顾问",
    likes: 2800,
    imageUrl: "https://picsum.photos/400/300?random=36",
    category: "fashion",
  },

  // food分类 (15条)
  {
    id: 37,
    title: "在家也能做的米其林甜点",
    content: "简单易上手的法式甜点",
    author: "甜点师",
    likes: 4800,
    imageUrl: "https://picsum.photos/400/300?random=37",
    category: "food",
  },
  {
    id: 38,
    title: "30分钟搞定的快手晚餐",
    content: "上班族必备菜谱",
    author: "家常菜达人",
    likes: 3500,
    imageUrl: "https://picsum.photos/400/300?random=38",
    category: "food",
  },
  {
    id: 39,
    title: "自制网红奶茶教程",
    content: "无添加更健康",
    author: "饮品师",
    likes: 6200,
    imageUrl: "https://picsum.photos/400/300?random=39",
    category: "food",
  },
  {
    id: 40,
    title: "夏日清爽沙拉合集",
    content: "低卡美味，减脂必备",
    author: "健身餐厨师",
    likes: 3900,
    imageUrl: "https://picsum.photos/400/300?random=40",
    category: "food",
  },
  {
    id: 41,
    title: "零基础学做面包",
    content: "从入门到精通的烘焙指南",
    author: "面包师",
    likes: 5100,
    imageUrl: "https://picsum.photos/400/300?random=41",
    category: "food",
  },
  {
    id: 42,
    title: "川菜家常菜做法",
    content: "麻辣鲜香，开胃下饭",
    author: "川菜大厨",
    likes: 4300,
    imageUrl: "https://picsum.photos/400/300?random=42",
    category: "food",
  },
  {
    id: 43,
    title: "日式拉面在家做",
    content: "汤底秘诀大公开",
    author: "日料厨师",
    likes: 3700,
    imageUrl: "https://picsum.photos/400/300?random=43",
    category: "food",
  },
  {
    id: 44,
    title: "适合早餐的10种粥品",
    content: "营养丰富，易于消化",
    author: "养生达人",
    likes: 2900,
    imageUrl: "https://picsum.photos/400/300?random=44",
    category: "food",
  },
  {
    id: 45,
    title: "自制健康零食",
    content: "无添加剂，孩子也能吃",
    author: "宝妈厨房",
    likes: 4600,
    imageUrl: "https://picsum.photos/400/300?random=45",
    category: "food",
  },
  {
    id: 46,
    title: "海鲜烹饪小技巧",
    content: "如何保持海鲜的鲜嫩",
    author: "海鲜料理师",
    likes: 3200,
    imageUrl: "https://picsum.photos/400/300?random=46",
    category: "food",
  },
  {
    id: 47,
    title: "素食者的蛋白质来源",
    content: "美味又营养的素食菜谱",
    author: "素食厨师",
    likes: 2800,
    imageUrl: "https://picsum.photos/400/300?random=47",
    category: "food",
  },
  {
    id: 48,
    title: "烧烤酱料配方大全",
    content: "自制酱料更美味",
    author: "烧烤达人",
    likes: 5300,
    imageUrl: "https://picsum.photos/400/300?random=48",
    category: "food",
  },
  {
    id: 49,
    title: "儿童开胃菜做法",
    content: "让孩子爱上吃饭",
    author: "儿童营养师",
    likes: 3800,
    imageUrl: "https://picsum.photos/400/300?random=49",
    category: "food",
  },
  {
    id: 50,
    title: "秋季滋补汤品推荐",
    content: "暖心暖胃，增强免疫力",
    author: "中医食疗师",
    likes: 4100,
    imageUrl: "https://picsum.photos/400/300?random=50",
    category: "food",
  },
  {
    id: 51,
    title: "意式料理在家做",
    content: "简单美味的意大利面做法",
    author: "西餐厨师",
    likes: 3600,
    imageUrl: "https://picsum.photos/400/300?random=51",
    category: "food",
  },

  // makeup分类 (10条)
  {
    id: 52,
    title: "新手化妆步骤详解",
    content: "从底妆到定妆的完整流程",
    author: "美妆教程",
    likes: 6800,
    imageUrl: "https://picsum.photos/400/300?random=52",
    category: "makeup",
  },
  {
    id: 53,
    title: "适合职场的淡妆技巧",
    content: "自然得体，提升气色",
    author: "职业化妆师",
    likes: 4200,
    imageUrl: "https://picsum.photos/400/300?random=53",
    category: "makeup",
  },
  {
    id: 54,
    title: "干性皮肤的底妆选择",
    content: "告别卡粉浮粉",
    author: "美妆博主",
    likes: 5300,
    imageUrl: "https://picsum.photos/400/300?random=54",
    category: "makeup",
  },
  {
    id: 55,
    title: "眼妆新手教程",
    content: "从单眼皮到双眼皮的不同画法",
    author: "眼妆专家",
    likes: 4700,
    imageUrl: "https://picsum.photos/400/300?random=55",
    category: "makeup",
  },
  {
    id: 56,
    title: "夏季不脱妆技巧",
    content: "持久妆容的秘密",
    author: "彩妆师",
    likes: 5900,
    imageUrl: "https://picsum.photos/400/300?random=56",
    category: "makeup",
  },
  {
    id: 57,
    title: "口红颜色选择指南",
    content: "根据肤色选对口红",
    author: "美妆达人",
    likes: 4300,
    imageUrl: "https://picsum.photos/400/300?random=57",
    category: "makeup",
  },
  {
    id: 58,
    title: "5分钟快速妆容",
    content: "适合赶时间的早晨",
    author: "效率美妆",
    likes: 3800,
    imageUrl: "https://picsum.photos/400/300?random=58",
    category: "makeup",
  },
  {
    id: 59,
    title: "卸妆的正确步骤",
    content: "彻底清洁，保护肌肤",
    author: "护肤专家",
    likes: 4600,
    imageUrl: "https://picsum.photos/400/300?random=59",
    category: "makeup",
  },
  {
    id: 60,
    title: "秋冬季节的唇妆护理",
    content: "告别干燥脱皮",
    author: "唇部护理师",
    likes: 3200,
    imageUrl: "https://picsum.photos/400/300?random=60",
    category: "makeup",
  },
  {
    id: 61,
    title: "节日派对妆容教程",
    content: "闪耀全场的妆容技巧",
    author: "派对妆专家",
    likes: 5100,
    imageUrl: "https://picsum.photos/400/300?random=61",
    category: "makeup",
  },

  // movie分类 (8条)
  {
    id: 62,
    title: "2023年必看的科幻电影",
    content: "脑洞大开的视觉盛宴",
    author: "影评人",
    likes: 3800,
    imageUrl: "https://picsum.photos/400/300?random=62",
    category: "movie",
  },
  {
    id: 63,
    title: "经典悬疑电影推荐",
    content: "烧脑又过瘾的佳作",
    author: "悬疑爱好者",
    likes: 4200,
    imageUrl: "https://picsum.photos/400/300?random=63",
    category: "movie",
  },
  {
    id: 64,
    title: "宫崎骏动画电影盘点",
    content: "温暖治愈的童话世界",
    author: "动画迷",
    likes: 5600,
    imageUrl: "https://picsum.photos/400/300?random=64",
    category: "movie",
  },
  {
    id: 65,
    title: "奥斯卡获奖影片解析",
    content: "从专业角度看电影",
    author: "电影学者",
    likes: 3100,
    imageUrl: "https://picsum.photos/400/300?random=65",
    category: "movie",
  },
  {
    id: 66,
    title: "适合情侣观看的浪漫电影",
    content: "甜蜜又感人的爱情故事",
    author: "情侣指南",
    likes: 4700,
    imageUrl: "https://picsum.photos/400/300?random=66",
    category: "movie",
  },
  {
    id: 67,
    title: "高评分纪录片推荐",
    content: "真实比虚构更精彩",
    author: "纪录片迷",
    likes: 2900,
    imageUrl: "https://picsum.photos/400/300?random=67",
    category: "movie",
  },
  {
    id: 68,
    title: "漫威电影宇宙时间线整理",
    content: "从钢铁侠到复仇者联盟",
    author: "漫威粉丝",
    likes: 6300,
    imageUrl: "https://picsum.photos/400/300?random=68",
    category: "movie",
  },
  {
    id: 69,
    title: "韩国犯罪电影精选",
    content: "紧张刺激的剧情反转",
    author: "韩影爱好者",
    likes: 3500,
    imageUrl: "https://picsum.photos/400/300?random=69",
    category: "movie",
  },

  // workplace分类 (7条)
  {
    id: 70,
    title: "职场新人的生存法则",
    content: "快速融入团队的技巧",
    author: "HR总监",
    likes: 4200,
    imageUrl: "https://picsum.photos/400/300?random=70",
    category: "workplace",
  },
  {
    id: 71,
    title: "高效会议的组织技巧",
    content: "告别冗长无效的会议",
    author: "项目经理",
    likes: 3100,
    imageUrl: "https://picsum.photos/400/300?random=71",
    category: "workplace",
  },
  {
    id: 72,
    title: "职场沟通的艺术",
    content: "如何清晰表达自己的想法",
    author: "沟通教练",
    likes: 3800,
    imageUrl: "https://picsum.photos/400/300?random=72",
    category: "workplace",
  },
  {
    id: 73,
    title: "职业规划的5个步骤",
    content: "找到适合自己的发展方向",
    author: "职业顾问",
    likes: 4500,
    imageUrl: "https://picsum.photos/400/300?random=73",
    category: "workplace",
  },
  {
    id: 74,
    title: "如何应对职场压力",
    content: "保持身心健康的方法",
    author: "心理咨询师",
    likes: 3600,
    imageUrl: "https://picsum.photos/400/300?random=74",
    category: "workplace",
  },
  {
    id: 75,
    title: "远程工作效率提升指南",
    content: "居家办公也能高效产出",
    author: "远程工作者",
    likes: 5200,
    imageUrl: "https://picsum.photos/400/300?random=75",
    category: "workplace",
  },
  {
    id: 76,
    title: "职场晋升的关键因素",
    content: "除了能力之外的重要特质",
    author: "高管分享",
    likes: 4800,
    imageUrl: "https://picsum.photos/400/300?random=76",
    category: "workplace",
  },

  // emotion分类 (6条)
  {
    id: 77,
    title: "如何克服社交恐惧",
    content: "逐步建立社交自信",
    author: "心理医生",
    likes: 5300,
    imageUrl: "https://picsum.photos/400/300?random=77",
    category: "emotion",
  },
  {
    id: 78,
    title: "恋爱中的边界感",
    content: "保持独立又亲密的关系",
    author: "情感咨询师",
    likes: 4600,
    imageUrl: "https://picsum.photos/400/300?random=78",
    category: "emotion",
  },
  {
    id: 79,
    title: "应对焦虑的实用方法",
    content: "日常可操作的减压技巧",
    author: "情绪管理师",
    likes: 6100,
    imageUrl: "https://picsum.photos/400/300?random=79",
    category: "emotion",
  },
  {
    id: 80,
    title: "与父母和解的过程",
    content: "理解与被理解的旅程",
    author: "亲子关系专家",
    likes: 4900,
    imageUrl: "https://picsum.photos/400/300?random=80",
    category: "emotion",
  },
  {
    id: 81,
    title: "分手后的自我疗愈",
    content: "走出失恋阴影的方法",
    author: "失恋顾问",
    likes: 5800,
    imageUrl: "https://picsum.photos/400/300?random=81",
    category: "emotion",
  },
  {
    id: 82,
    title: "建立健康的亲密关系",
    content: "爱与被爱的能力",
    author: "婚姻咨询师",
    likes: 4300,
    imageUrl: "https://picsum.photos/400/300?random=82",
    category: "emotion",
  },

  // home分类 (8条)
  {
    id: 83,
    title: "小户型收纳技巧",
    content: "充分利用每一寸空间",
    author: "收纳专家",
    likes: 4700,
    imageUrl: "https://picsum.photos/400/300?random=83",
    category: "home",
  },
  {
    id: 84,
    title: "北欧风家居布置",
    content: "简约舒适的居住空间",
    author: "室内设计师",
    likes: 5200,
    imageUrl: "https://picsum.photos/400/300?random=84",
    category: "home",
  },
  {
    id: 85,
    title: "绿植在家居中的运用",
    content: "打造自然清新的家",
    author: "植物爱好者",
    likes: 3800,
    imageUrl: "https://picsum.photos/400/300?random=85",
    category: "home",
  },
  {
    id: 86,
    title: "厨房整理妙招",
    content: "让烹饪更高效愉悦",
    author: "家政达人",
    likes: 4100,
    imageUrl: "https://picsum.photos/400/300?random=86",
    category: "home",
  },
  {
    id: 87,
    title: "低成本家居改造",
    content: "小改变带来大不同",
    author: "DIY爱好者",
    likes: 3600,
    imageUrl: "https://picsum.photos/400/300?random=87",
    category: "home",
  },
  {
    id: 88,
    title: "智能家居设备推荐",
    content: "提升生活品质的科技产品",
    author: "科技家居达人",
    likes: 4900,
    imageUrl: "https://picsum.photos/400/300?random=88",
    category: "home",
  },
  {
    id: 89,
    title: "卧室布置的风水讲究",
    content: "助你拥有好睡眠",
    author: "风水顾问",
    likes: 3200,
    imageUrl: "https://picsum.photos/400/300?random=89",
    category: "home",
  },
  {
    id: 90,
    title: "浴室清洁与整理",
    content: "保持洁净清爽的小技巧",
    author: "清洁专家",
    likes: 2900,
    imageUrl: "https://picsum.photos/400/300?random=90",
    category: "home",
  },

  // game分类 (5条)
  {
    id: 91,
    title: "王者荣耀新手英雄推荐",
    content: "容易上手的强势英雄",
    author: "游戏教练",
    likes: 7200,
    imageUrl: "https://picsum.photos/400/300?random=91",
    category: "game",
  },
  {
    id: 92,
    title: "塞尔达传说：王国之泪探索指南",
    content: "隐藏任务与彩蛋",
    author: "任天堂粉丝",
    likes: 5800,
    imageUrl: "https://picsum.photos/400/300?random=92",
    category: "game",
  },
  {
    id: 93,
    title: "电竞选手的日常训练",
    content: "专业玩家的一天",
    author: "职业选手",
    likes: 4300,
    imageUrl: "https://picsum.photos/400/300?random=93",
    category: "game",
  },
  {
    id: 94,
    title: "适合情侣玩的合作游戏",
    content: "增进感情的互动游戏",
    author: "游戏情侣",
    likes: 3700,
    imageUrl: "https://picsum.photos/400/300?random=94",
    category: "game",
  },
  {
    id: 95,
    title: "怀旧游戏盘点",
    content: "那些陪伴我们成长的游戏",
    author: "老玩家",
    likes: 4900,
    imageUrl: "https://picsum.photos/400/300?random=95",
    category: "game",
  },

  // travel分类 (10条)
  {
    id: 96,
    title: "云南小众旅行地推荐",
    content: "避开人潮的秘境",
    author: "旅行博主",
    likes: 5300,
    imageUrl: "https://picsum.photos/400/300?random=96",
    category: "travel",
  },
  {
    id: 97,
    title: "日本关西自由行攻略",
    content: "京都、大阪、奈良7日游",
    author: "日本通",
    likes: 4800,
    imageUrl: "https://picsum.photos/400/300?random=97",
    category: "travel",
  },
  {
    id: 98,
    title: "独自旅行的注意事项",
    content: "安全又自在的 solo trip",
    author: "独行侠",
    likes: 3900,
    imageUrl: "https://picsum.photos/400/300?random=98",
    category: "travel",
  },
  {
    id: 99,
    title: "自驾游装备清单",
    content: "说走就走的旅行准备",
    author: "自驾爱好者",
    likes: 4200,
    imageUrl: "https://picsum.photos/400/300?random=99",
    category: "travel",
  },
  {
    id: 100,
    title: "东南亚海岛推荐",
    content: "性价比高的度假胜地",
    author: "海岛控",
    likes: 5600,
    imageUrl: "https://picsum.photos/400/300?random=100",
    category: "travel",
  },
  {
    id: 101,
    title: "西藏旅行注意事项",
    content: "高原反应预防与应对",
    author: "西藏向导",
    likes: 4100,
    imageUrl: "https://picsum.photos/400/300?random=101",
    category: "travel",
  },
  {
    id: 102,
    title: "欧洲火车旅行攻略",
    content: "跨国交通与铁路通票",
    author: "欧洲旅行达人",
    likes: 3700,
    imageUrl: "https://picsum.photos/400/300?random=102",
    category: "travel",
  },
  {
    id: 103,
    title: "摄影爱好者的旅行目的地",
    content: "绝美风景出片率高",
    author: "旅行摄影师",
    likes: 5200,
    imageUrl: "https://picsum.photos/400/300?random=103",
    category: "travel",
  },
  {
    id: 104,
    title: "适合亲子游的主题乐园",
    content: "带娃旅行的好去处",
    author: "亲子游攻略",
    likes: 4500,
    imageUrl: "https://picsum.photos/400/300?random=104",
    category: "travel",
  },
  {
    id: 105,
    title: "旅行中的美食探索",
    content: "各地特色美食指南",
    author: "美食旅行家",
    likes: 4900,
    imageUrl: "https://picsum.photos/400/300?random=105",
    category: "travel",
  },

  // exercise分类 (4条)
  {
    id: 106,
    title: "办公室微运动指南",
    content: "久坐族的健康救星",
    author: "办公室健身教练",
    likes: 4300,
    imageUrl: "https://picsum.photos/400/300?random=106",
    category: "exercise",
  },
  {
    id: 107,
    title: "初学者跑步计划",
    content: "从跑不动到轻松跑5公里",
    author: "马拉松选手",
    likes: 3800,
    imageUrl: "https://picsum.photos/400/300?random=107",
    category: "exercise",
  },
  {
    id: 108,
    title: "居家瑜伽入门动作",
    content: "改善体态，缓解压力",
    author: "瑜伽导师",
    likes: 4600,
    imageUrl: "https://picsum.photos/400/300?random=108",
    category: "exercise",
  },
  {
    id: 109,
    title: "徒手健身动作大全",
    content: "不用器械也能练全身",
    author: "健身达人",
    likes: 5100,
    imageUrl: "https://picsum.photos/400/300?random=109",
    category: "exercise",
  },
];
